title: HomeLab Site
description: Projects, documentation and ideas about home, garden, technology and energy.
url: "https://dstegmaier48-png.github.io"
baseurl: "/homelabsite"
lang: en
theme: minima

header_pages:
  - homelab/index.md
  - renovation/index.md
  - hidde-gardening/index.md
  - diy/index.md
  - digital/index.md
  - energy/index.md
  - legal-notice.md
  - privacy-policy.md

exclude:
  - README.md
  - templates
  - Gemfile
  - Gemfile.lock
